### ISSUE TITLE
作者您好,请问这个系列还打算继续更新下去吗?

### ISSUE THREAD

**Issue by John-Ralph** [yizhen20133868/MIT-Linear-Algebra-Notes#1]
前几讲的笔记做得非常好,渴望见到后面课程的笔记,谢谢!

**Comment by qinlibo-hit** [comment]
你好，会更新下去，感谢认可~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ralph"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月20日(星期一) 上午10:49
收件人:&nbsp;"yizhen20133868/MIT-Linear-Algebra-Notes"<MIT-Linear-Algebra-Notes@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yizhen20133868/MIT-Linear-Algebra-Notes] 作者您好,请问这个系列还打算继续更新下去吗? (#1)




前几讲的笔记做得非常好,渴望见到后面课程的笔记,谢谢!
