### ISSUE TITLE
第四课、置换矩阵有一处小错误

### ISSUE THREAD

**Issue by zerd-wanger** [yizhen20133868/MIT-Linear-Algebra-Notes#8]
“一个经典的例子就是：在消元过程中，当矩阵主元 位置上面不是 1 时，我们就需要用行变换将主元位置换回 1。”
应该说主元位置上是0时，我们需要通过行变换来将主元换成0

**Comment by KB-Ding** [comment]
感谢您的建议，这里表述不太清楚，我们已经更新了第四课的相关描述。
这里想表达的是：在消元过程中，当矩阵主元位置上面为0时，我们就需要用行变换将主元位置换为非0数。具体可以参考“第二课 / 2.1 / 注” 中的部分。
